<?php
$modversion['name'] = _MI_XPWEATHER_NAME;
$modversion['version'] = "1.3a(J2.3a)";
$modversion['description'] = _MI_XPWEATHER_DESC;
$modversion['credits'] = "1.0 - 1.3 code by:<br />davidd<br />http://www.axarosenberg.com<br />French Language Translation<br />Olivier Blazy<br />olivier.blazy@wanadoo.fr<br />Logo Image by Vincent Roman<br />http://www.neutronbull.com/<br />And<br />1.3a(J-J2) edit by:<br />nao-pon<br />nao-pon@hypweb.net<br /><a href='http://hypweb.net/'>http://hypweb.net/</a>";
$modversion['author'] = "Original PHPNuke code by - James Nerlinger (jnj@infobin.com)<br />Original Adapte pour XOOPS rc3 par:<br />Philippe<br />http://www.web-liens.net";
$modversion['help'] = "The cache directory and files need to be set for both reading and writting by the account the webserver runs under";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = "0";
$modversion['image'] = "wweather.jpg";
$modversion['dirname'] = "XP-Weather";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "xpweather_userloc";
$modversion['tables'][1] = "xpweather_country";
$modversion['tables'][2] = "xpweather_region";
$modversion['tables'][3] = "xpweather_station";

// Menu
$modversion['hasMain'] = 1;

// block
$modversion['blocks'][1]['file'] = "block-XPWeather.php";
$modversion['blocks'][1]['name'] = "XP-Weather Block#1";
$modversion['blocks'][1]['description'] = "Block_XP-Weather#1";
$modversion['blocks'][1]['show_func'] = "disp_block_XPWeather";
$modversion['blocks'][1]['edit_func'] = "block_XPWeather_edit";
$modversion['blocks'][1]['options'] = "default";
$modversion['blocks'][1]['can_clone'] = true;

$modversion['blocks'][2]['file'] = "block-XPWeather.php";
$modversion['blocks'][2]['name'] = "XP-Weather Block#2";
$modversion['blocks'][2]['description'] = "Block_XP-Weather#2";
$modversion['blocks'][2]['show_func'] = "disp_block_XPWeather";
$modversion['blocks'][2]['edit_func'] = "block_XPWeather_edit";
$modversion['blocks'][2]['options'] = "default";
$modversion['blocks'][2]['can_clone'] = false;

$modversion['blocks'][3]['file'] = "block-XPWeather.php";
$modversion['blocks'][3]['name'] = "XP-Weather MultiBlock";
$modversion['blocks'][3]['description'] = "Multi station Block (XP-Weather)";
$modversion['blocks'][3]['show_func'] = "multi_block_XPWeather";
$modversion['blocks'][3]['edit_func'] = "multi_block_XPWeather_edit";
$modversion['blocks'][3]['options'] = "JAXX0085,USDC0001,UKXX0085,GMXX0007|180|4|multi";
$modversion['blocks'][3]['can_clone'] = true;

// Admin
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

//Config
$modversion['hasConfig'] = 1;
$modversion['config'][] = array(
	'name' => 'dev_id',
	'title' => '_MI_XPWEATHER_DEVID',
	'description' => '',
	'formtype' => 'textbox',
	'valuetype' => 'string',
	'default' => '',
	);
$modversion['config'][] = array(
	'name' => 'dev_key',
	'title' => '_MI_XPWEATHER_DEVKEY',
	'description' => '',
	'formtype' => 'textbox',
	'valuetype' => 'string',
	'default' => '',
	);

// On Update
if( ! empty( $_POST['fct'] ) && ! empty( $_POST['op'] ) && $_POST['fct'] == 'modulesadmin' && $_POST['op'] == 'update_ok' && $_POST['dirname'] == $modversion['dirname'] ) {
	include dirname( __FILE__ ) . "/include/onupdate.inc.php" ;
}
?>